name: 01 Verify Environment

on:
  push:
    paths:
      - 'default_dev.nix'
      - '.github/workflows/01-env.yaml'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v14
        with:
          name: rstats-on-nix
          # Optional: Provide key explicitly if needed for non-authenticated public pull
          extraPullNames: rstats-on-nix
      
      - name: Check Tools
        run: |
          nix-shell --pure default_dev.nix --run "R --version"
          nix-shell --pure default_dev.nix --run "aws --version"
