# This workflow is deprecated and replaced by:
# - ci-env.yaml
# - analysis.yaml
# - website.yaml
name: Deprecated Workflow
on: 
  workflow_dispatch:
jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated."